# Generated by Django 2.2.3 on 2019-07-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20190712_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
