# Generated by Django 2.2.3 on 2019-07-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20190715_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latlng',
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
